export interface Friend {
    id: number;
    initials: string;
    name: string;
    messages: number;
    daysAsFriends: number;
    streak: number;
    mutualFriends: number;
    avatar: any;
    city: string;
    state: string;
    country: string;
    age: number;
    gender: string;
}

export const friendsData: Friend[] = [
    { 
        id: 1, 
        initials: 'JP', 
        name: 'Jpp123', 
        messages: 1298, 
        daysAsFriends: 116, 
        streak: 7, 
        mutualFriends: 12,
        avatar: require('../assets/images/profile_picture.jpg'),
        city: "Seattle",
        state: "Washington",
        country: "United States",
        age: 24,
        gender: "Male"
    },
    { 
        id: 2, 
        initials: 'AD', 
        name: 'AlexD33', 
        messages: 876, 
        daysAsFriends: 89, 
        streak: 33, 
        mutualFriends: 8,
        avatar: require('../assets/images/profile_icon.png'),
        city: "Boston",
        state: "Massachusetts",
        country: "United States",
        age: 19,
        gender: "Non-binary"
    },
    { 
        id: 3, 
        initials: 'PC', 
        name: 'PChak55', 
        messages: 954, 
        daysAsFriends: 124, 
        streak: 42, 
        mutualFriends: 15,
        avatar: require('../assets/images/profile-800x800.png'),
        city: "Chicago",
        state: "Illinois",
        country: "United States",
        age: 27,
        gender: "Female"
    },
    { 
        id: 4, 
        initials: 'OD', 
        name: 'OnDeck02', 
        messages: 445, 
        daysAsFriends: 67, 
        streak: 29, 
        mutualFriends: 6,
        avatar: require('../assets/images/profile2-500x500.png'),
        city: "Austin",
        state: "Texas",
        country: "United States",
        age: 22,
        gender: "Male"
    },
    { 
        id: 5, 
        initials: 'AJ', 
        name: 'AJones01', 
        messages: 789, 
        daysAsFriends: 78, 
        streak: 22, 
        mutualFriends: 19,
        avatar: require('../assets/images/profile3-500x500.png'),
        city: "Portland",
        state: "Oregon",
        country: "United States",
        age: 25,
        gender: "Female"
    },
    { 
        id: 6, 
        initials: 'HP', 
        name: 'Hpp123', 
        messages: 567, 
        daysAsFriends: 45, 
        streak: 0, 
        mutualFriends: 7,
        avatar: require('../assets/images/profile_picture.jpg'),
        city: "Denver",
        state: "Colorado",
        country: "United States",
        age: 30,
        gender: "Other"
    },
    { 
        id: 7, 
        initials: 'TP', 
        name: 'Tpp123', 
        messages: 234, 
        daysAsFriends: 23, 
        streak: 0, 
        mutualFriends: 4,
        avatar: require('../assets/images/profile_picture.jpg'),
        city: "Miami",
        state: "Florida",
        country: "United States",
        age: 21,
        gender: "Male"
    },
    { 
        id: 8, 
        initials: 'MP', 
        name: 'Mike123', 
        messages: 712, 
        daysAsFriends: 118, 
        streak: 0, 
        mutualFriends: 21,
        avatar: require('../assets/images/profile_picture.jpg'),
        city: "Nashville",
        state: "Tennessee",
        country: "United States",
        age: 26,
        gender: "Female"
    },
    { 
        id: 9, 
        initials: 'WP', 
        name: 'Wpp123', 
        messages: 345, 
        daysAsFriends: 56, 
        streak: 0, 
        mutualFriends: 9,
        avatar: require('../assets/images/profile_picture.jpg'),
        city: "San Francisco",
        state: "California",
        country: "United States",
        age: 23,
        gender: "Prefer not to say"
    },
    { 
        id: 10,
        initials: 'RK',
        name: 'RyanK44',
        messages: 892,
        daysAsFriends: 45,
        streak: 6,
        mutualFriends: 14,
        avatar: require('../assets/images/profile_icon.png'),
        city: "Philadelphia",
        state: "Pennsylvania",
        country: "United States",
        age: 28,
        gender: "Male"
    },
    {
        id: 11,
        initials: 'ML',
        name: 'MikeL88',
        messages: 1102,
        daysAsFriends: 67,
        streak: 0,
        mutualFriends: 16,
        avatar: require('../assets/images/profile-800x800.png'),
        city: "Las Vegas",
        state: "Nevada",
        country: "United States",
        age: 24,
        gender: "Male"
    },
    {
        id: 12,
        initials: 'SB',
        name: 'SamB22',
        messages: 445,
        daysAsFriends: 78,
        streak: 0,
        mutualFriends: 7,
        avatar: require('../assets/images/profile2-500x500.png'),
        city: "Houston",
        state: "Texas",
        country: "United States",
        age: 20,
        gender: "Prefer not to say"
    },
    {
        id: 13,
        initials: 'JD',
        name: 'JoshD99',
        messages: 678,
        daysAsFriends: 62,
        streak: 0,
        mutualFriends: 11,
        avatar: require('../assets/images/profile3-500x500.png'),
        city: "San Diego",
        state: "California",
        country: "United States",
        age: 29,
        gender: "Male"
    },
    {
        id: 14,
        initials: 'EW',
        name: 'EricW77',
        messages: 334,
        daysAsFriends: 45,
        streak: 0,
        mutualFriends: 5,
        avatar: require('../assets/images/profile_picture.jpg'),
        city: "Phoenix",
        state: "Arizona",
        country: "United States",
        age: 25,
        gender: "Male"
    },
    {
        id: 15,
        initials: 'CM',
        name: 'ChrisM11',
        messages: 97,
        daysAsFriends: 89,
        streak: 0,
        mutualFriends: 18,
        avatar: require('../assets/images/profile_icon.png'),
        city: "Atlanta",
        state: "Georgia",
        country: "United States",
        age: 23,
        gender: "Non-binary"
    },
    {
        id: 16,
        initials: 'BH',
        name: 'BenH66',
        messages: 556,
        daysAsFriends: 92,
        streak: 0,
        mutualFriends: 10,
        avatar: require('../assets/images/profile-800x800.png'),
        city: "Dallas",
        state: "Texas",
        country: "United States",
        age: 27,
        gender: "Male"
    },
    {
        id: 17,
        initials: 'NK',
        name: 'NickK33',
        messages: 1208,
        daysAsFriends: 21,
        streak: 0,
        mutualFriends: 20,
        avatar: require('../assets/images/profile2-500x500.png'),
        city: "Oakland",
        state: "California",
        country: "United States",
        age: 22,
        gender: "Male"
    },
    {
        id: 18,
        initials: 'DM',
        name: 'DaveM45',
        messages: 289,
        daysAsFriends: 34,
        streak: 0,
        mutualFriends: 6,
        avatar: require('../assets/images/profile3-500x500.png'),
        city: "Minneapolis",
        state: "Minnesota",
        country: "United States",
        age: 26,
        gender: "Male"
    },
    {
        id: 19,
        initials: 'LS',
        name: 'LukeS91',
        messages: 723,
        daysAsFriends: 13,
        streak: 0,
        mutualFriends: 13,
        avatar: require('../assets/images/profile_picture.jpg'),
        city: "Sacramento",
        state: "California",
        country: "United States",
        age: 24,
        gender: "Male"
    },
    {
        id: 20,
        initials: 'AR',
        name: 'AndyR55',
        messages: 445,
        daysAsFriends: 67,
        streak: 0,
        mutualFriends: 8,
        avatar: require('../assets/images/profile_icon.png'),
        city: "Cleveland",
        state: "Ohio",
        country: "United States",
        age: 28,
        gender: "Female"
    },
    {
        id: 21,
        initials: 'TM',
        name: 'TomM78',
        messages: 834,
        daysAsFriends: 16,
        streak: 0,
        mutualFriends: 15,
        avatar: require('../assets/images/profile-800x800.png'),
        city: "New York",
        state: "New York",
        country: "United States",
        age: 30,
        gender: "Male"
    },
    {
        id: 22,
        initials: 'PW',
        name: 'PeteW23',
        messages: 567,
        daysAsFriends: 88,
        streak: 0,
        mutualFriends: 9,
        avatar: require('../assets/images/profile2-500x500.png'),
        city: "Los Angeles",
        state: "California",
        country: "United States",
        age: 25,
        gender: "Male"
    },
    {
        id: 23,
        initials: 'GK',
        name: 'GregK67',
        messages: 1156,
        daysAsFriends: 18,
        streak: 0,
        mutualFriends: 17,
        avatar: require('../assets/images/profile3-500x500.png'),
        city: "San Jose",
        state: "California",
        country: "United States",
        age: 21,
        gender: "Other"
    },
    {
        id: 24,
        initials: 'RS',
        name: 'RobS89',
        messages: 398,
        daysAsFriends: 56,
        streak: 0,
        mutualFriends: 7,
        avatar: require('../assets/images/profile_picture.jpg'),
        city: "Detroit",
        state: "Michigan",
        country: "United States",
        age: 19,
        gender: "Male"
    },
    {
        id: 25,
        initials: 'KL',
        name: 'KevinL12',
        messages: 678,
        daysAsFriends: 184,
        streak: 0,
        mutualFriends: 12,
        avatar: require('../assets/images/profile_icon.png'),
        city: "Washington",
        state: "District of Columbia",
        country: "United States",
        age: 26,
        gender: "Male"
    }
];