export const topUsCitiesByState = {
    Alabama: ["Birmingham", "Montgomery", "Huntsville"],
    Alaska: ["Anchorage", "Fairbanks", "Juneau"],
    Arizona: [
      "Phoenix",
      "Tucson",
      "Mesa",
      "Chandler",
      "Scottsdale",
      "Glendale",
      "Gilbert",
      "Tempe",
      "Peoria",
      "Surprise",
      "Yuma",
      "Avondale",
      "Goodyear",
      "Flagstaff",
      "Buckeye",
    ],
    Arkansas: ["Little Rock", "Fort Smith", "Fayetteville"],
    California: [
      "Los Angeles",
      "San Diego",
      "San Jose",
      "San Francisco",
      "Fresno",
      "Sacramento",
      "Long Beach",
      "Oakland",
      "Bakersfield",
      "Anaheim",
      "Santa Ana",
      "Riverside",
      "Stockton",
      "Chula Vista",
      "Irvine",
    ],
    Colorado: [
      "Denver",
      "Colorado Springs",
      "Aurora",
      "Fort Collins",
      "Lakewood",
      "Thornton",
      "Arvada",
      "Westminster",
      "Pueblo",
      "Greeley",
      "Centennial",
      "Boulder",
      "Longmont",
      "Loveland",
      "Broomfield",
    ],
    Connecticut: ["Bridgeport", "New Haven", "Stamford"],
    Delaware: ["Wilmington", "Dover", "Newark"],
    DistrictOfColumbia: ["Washington"],
    Florida: [
      "Jacksonville",
      "Miami",
      "Tampa",
      "Orlando",
      "St. Petersburg",
      "Hialeah",
      "Port St. Lucie",
      "Cape Coral",
      "Tallahassee",
      "Fort Lauderdale",
      "Pembroke Pines",
      "Hollywood",
      "Miramar",
      "Gainesville",
      "Coral Springs",
    ],
    Georgia: [
      "Atlanta",
      "Augusta",
      "Columbus",
      "Macon",
      "Savannah",
      "Athens",
      "Sandy Springs",
      "South Fulton",
      "Roswell",
      "Johns Creek",
      "Warner Robins",
      "Albany",
      "Alpharetta",
      "Marietta",
      "Smyrna",
    ],
    Hawaii: ["Honolulu", "East Honolulu", "Pearl City"],
    Idaho: ["Boise", "Meridian", "Nampa"],
    Illinois: [
      "Chicago",
      "Aurora",
      "Naperville",
      "Joliet",
      "Rockford",
      "Springfield",
      "Elgin",
      "Peoria",
      "Champaign",
      "Waukegan",
      "Cicero",
      "Bloomington",
      "Arlington Heights",
      "Evanston",
      "Schaumburg",
    ],
    Indiana: [
      "Indianapolis",
      "Fort Wayne",
      "Evansville",
      "South Bend",
      "Carmel",
      "Fishers",
      "Bloomington",
      "Hammond",
      "Gary",
    ],
    Iowa: ["Des Moines", "Cedar Rapids", "Davenport"],
    Kansas: ["Wichita", "Overland Park", "Kansas City", "Olathe", "Topeka"],
    Kentucky: ["Louisville", "Lexington", "Bowling Green"],
    Louisiana: ["New Orleans", "Baton Rouge", "Shreveport"],
    Maine: ["Portland", "Lewiston", "Bangor"],
    Maryland: ["Baltimore", "Frederick", "Rockville"],
    Massachusetts: ["Boston", "Worcester", "Springfield", "Cambridge", "Lowell", "Brockton"],
    Michigan: [
      "Detroit",
      "Grand Rapids",
      "Warren",
      "Sterling Heights",
      "Ann Arbor",
      "Lansing",
      "Flint",
      "Dearborn",
      "Livonia",
      "Westland",
    ],
    Minnesota: ["Minneapolis", "St. Paul", "Rochester"],
    Mississippi: ["Jackson", "Gulfport", "Southaven"],
    Missouri: ["Kansas City", "St. Louis", "Springfield", "Columbia", "Independence"],
    Montana: ["Billings", "Missoula", "Great Falls"],
    Nebraska: ["Omaha", "Lincoln", "Bellevue"],
    Nevada: ["Las Vegas", "Henderson", "Reno", "North Las Vegas", "Sparks"],
    NewHampshire: ["Manchester", "Nashua", "Concord"],
    NewJersey: ["Newark", "Jersey City", "Paterson", "Elizabeth", "Edison"],
    NewMexico: ["Albuquerque", "Las Cruces", "Rio Rancho"],
    NewYork: ["New York City", "Buffalo", "Rochester", "Yonkers", "Syracuse"],
    NorthCarolina: ["Charlotte", "Raleigh", "Greensboro", "Durham", "Winston-Salem", "Fayetteville", "Cary"],
    NorthDakota: ["Fargo", "Bismarck", "Grand Forks"],
    Ohio: ["Columbus", "Cleveland", "Cincinnati", "Toledo", "Akron"],
    Oklahoma: ["Oklahoma City", "Tulsa", "Norman", "Broken Arrow"],
    Oregon: ["Portland", "Salem", "Eugene"],
    Pennsylvania: ["Philadelphia", "Pittsburgh", "Allentown"],
    RhodeIsland: ["Providence", "Warwick", "Cranston"],
    SouthCarolina: ["Charleston", "Columbia", "North Charleston"],
    SouthDakota: ["Sioux Falls", "Rapid City", "Aberdeen"],
    Tennessee: ["Memphis", "Nashville", "Knoxville"],
    Texas: ["Houston", "San Antonio", "Dallas", "Austin", "Fort Worth"],
    Utah: ["Salt Lake City", "West Valley City", "Provo"],
    Vermont: ["Burlington", "South Burlington", "Rutland"],
    Virginia: ["Virginia Beach", "Norfolk", "Chesapeake"],
    Washington: ["Seattle", "Spokane", "Tacoma"],
    WestVirginia: ["Charleston", "Huntington", "Morgantown"],
    Wisconsin: ["Milwaukee", "Madison", "Green Bay"],
    Wyoming: ["Cheyenne", "Casper", "Laramie"],
  } as const;
  
  export type StateName = keyof typeof topUsCitiesByState;
  export type CityName = typeof topUsCitiesByState[StateName][number];
  