export const topUsCities = [
    "Albuquerque",
    "Anaheim",
    "Anchorage",
    "Arlington",
    "Atlanta",
    "Aurora",
    "Austin",
    "Bakersfield",
    "Baltimore",
    "Boston",
    "Charlotte",
    "Cincinnati",
    "Cleveland",
    "Colorado Springs",
    "Columbus",
    "Corpus Christi",
    "Dallas",
    "Denver",
    "Detroit",
    "Durham",
    "El Paso",
    "Fort Worth",
    "Fresno",
    "Greensboro",
    "Henderson",
    "Honolulu",
    "Houston",
    "Indianapolis",
    "Irvine",
    "Jacksonville",
    "Jersey City",
    "Kansas City",
    "Las Vegas",
    "Lexington",
    "Lincoln",
    "Long Beach",
    "Los Angeles",
    "Louisville",
    "Memphis",
    "Mesa",
    "Miami",
    "Milwaukee",
    "Minneapolis",
    "Nashville",
    "New Orleans",
    "New York",
    "Newark",
    "North Las Vegas",
    "Oakland",
    "Oklahoma City",
    "Omaha",
    "Orlando",
    "Philadelphia",
    "Phoenix",
    "Pittsburgh",
    "Plano",
    "Portland",
    "Raleigh",
    "Riverside",
    "Sacramento",
    "Saint Paul",
    "San Antonio",
    "San Diego",
    "San Francisco",
    "San Jose",
    "Santa Ana",
    "Seattle",
    "St. Louis",
    "Stockton",
    "Tampa",
    "Tucson",
    "Tulsa",
    "Virginia Beach",
    "Washington",
    "Wichita"
] as const;

export type CityName = typeof topUsCities[number];